name: Run pytest

# Controls when the workflow will run
on:
    # 
    push:
        branches:
            - "main"
            - "backend/**"
    pull_request:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test-app:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Get api_key from GitHub secrets
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        steps:
            - name: Install libreoffice
              run: sudo apt install -y libreoffice
            - name: Install pandoc
              run: sudo apt install -y pandoc
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
            - name: Install poppler
              run: sudo apt install -y poppler-utils libpoppler-cpp-dev
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
                if [ -f frontend/requirements.txt ]; then pip install -r frontend/requirements.txt; fi
                if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
            - name: Test with pytest-cov
              run: |
                coverage run -m pytest -v -s
            - name: Test with flake8
              run: |
                flake8 || echo
